### ISSUE TITLE
Updating user rights does not work

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/excel2map#31]
When saving the updated action to the database, an error occurs: 

Error: Trying to update unsynced document. Please save the document first by using insert() or addMany()

Maybe due to missing '$loki' parameter?
https://github.com/techfort/LokiJS/issues/297

**Comment by erikvullings** [comment]
Yes, you are correct and you are missing the '$loki' parameter. So after creating a new rule, you should have received the newly created rule in the response body, and use this one to update it. Not the rule you have created yourself (which doesn't contain the $loki index).
